### PR TITLE
Add an intro song to Audio folder

### PR DESCRIPTION
**Pull request by renatoDutraSilva**

### CODE REVIEW

**Comment by marcusrossel** [comment]
@renatoDutraSilva is this an accidental pull request?

**Comment by renatoDutraSilva** [comment]
@marcusrossel yes, this was my first attempt.

**Comment by marcusrossel** [comment]
@renatoDutraSilva could you perhaps delete this PR then if it is not meant to be merged?

**Comment by renatoDutraSilva** [comment]
@marcusrossel sorry.. done!

**Pull request closed without merging**
