### PR TITLE
Restructure and rename directories

### PR DESCRIPTION
**Pull request by garricn**

### CODE REVIEW

**Comment by garricn** [comment]
Oh! I thought .github just referenced something like `~/` My bad. I will re add.

**Comment by BasThomas** [comment]
If you could also address [this](https://github.com/SwiftCommunityPodcast/podcast/pull/36#issuecomment-466704749) that'd be 💯! 😇

**Comment by garricn** [comment]
> If you could also address [this](https://github.com/SwiftCommunityPodcast/podcast/pull/36#issuecomment-466704749) that'd be 💯! 😇

@BasThomas Will do. How should I fix it? Should I just delete `episode-related` as it seems like its just a duplicate of `speaker-suggestion`...?

**Comment by BasThomas** [comment]
Yeah, I’d suggest that. We can always add it again later. Cc @JulianKahnert 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JulianKahnert** [comment]
Hey @garricn sry for the late reply. This looks good to me 🙂

**Pull request merged**
