### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by JulianKahnert**
As @neversitdull states in #10: it might be a good idea to add categories for new issues. [GitHub helps us](https://help.github.com/articles/creating-issue-templates-for-your-repository/) with this.

I just created one example for a "new topic". Some other templates might be:
- 🎤 Speaker/Guest suggestion
- 🎧 Podcast Episode #X related
- 🏥 help wanted

What do you think?

### CODE REVIEW

**Comment by JulianKahnert** [comment]
@garricn any thoughts on this?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by garricn** [comment]
> @garricn any thoughts on this?
> 
> Sent with [GitHawk](http://githawk.com)

@JulianKahnert Hey Julian! I will take a look at this over the weekend. In the meantime, let's see if we can get some other people to look as well.

**Comment by alexito4** [comment]
Hi!
It looks good to me and I think having templtaes is gonna help a lot :) I was just wandering, maybe speaker suggestion should be in all of them? Maybe I want to propose a topic but I also known somebody that is an expert on it. 

Of course one can modify the PR itself but I'm just wondering it if would make sense to have this field in all of them.

**Comment by JulianKahnert** [comment]
@alexito4 thanks for your feedback. Hm...good question. As you pointed out, this might be a good case for extending the template for that specific issue.
What do you think about a "voting" on this case? 🤣 

👍 for **adding** the speaker suggestion field to the template
👎 for **leaving it the way it is**

**Comment by BasThomas** [comment]
Hey @JulianKahnert, what is the "episode related" template about? I don't get the idea of it.

**Comment by BasThomas** [comment]
There are some problems at the moment as well, as the name of `episode_related.md` is still `Speaker Suggestion`, which [breaks them](https://github.com/SwiftCommunityPodcast/podcast/blob/master/.github/ISSUE_TEMPLATE/episode-related.md) and does not show it as [an option](https://github.com/SwiftCommunityPodcast/podcast/issues/new/choose) when opening an issue.

**Comment by JulianKahnert** [comment]
Hey @BasThomas sry for the very late reply. I just looked into this and it seems to be fixed, right?

**Pull request merged**
